# Generated by Django 2.2.4 on 2019-08-14 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import oauth2client.contrib.django_util.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='CredentialsModel',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('credential', oauth2client.contrib.django_util.models.CredentialsField(null=True)),
                ('task', models.CharField(max_length=80, null=True)),
                ('updated_time', models.CharField(max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messages', models.TextField(blank=True, default='', max_length=5000)),
                ('token', models.TextField(blank=True, default='', max_length=5000)),
                ('contacts', models.TextField(blank=True, default='', max_length=5000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('messageId', models.TextField(max_length=5000, primary_key=True, serialize=False, unique=True)),
                ('reciever', models.TextField(blank=True, default='', max_length=5000)),
                ('sender', models.TextField(blank=True, default='', max_length=5000)),
                ('sender_email', models.TextField(blank=True, default='', max_length=5000)),
                ('date', models.TextField(blank=True, default='', max_length=5000)),
                ('subject', models.TextField(blank=True, default='', max_length=5000)),
                ('label', models.TextField(blank=True, default='', max_length=5000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
